name: learnk8s
video_course: no
exclude:
  - node_modules
  - yarn.lock
  - docker-compose.yml
  - package.json
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
sass:
  load_paths:
    - node_modules
  style: compressed
include: ["_pages"]
