[build]
  base    = "."
  publish = "_site"
  command = "yarn install && jekyll build && yarn minify"
[context.deploy-preview]
  command = "yarn install && jekyll build && yarn minify && echo -e \"\nDisallow: /\" >> _site/robots.txt"
