[build]
  base    = "."
  publish = "_site"
  command = "npm install && jekyll build && npm run minify && npm run build"
[context.deploy-preview]
  NODE_ENV = "preview"
  command = "npm install && jekyll build && npm run minify && echo -e \"\nDisallow: /\" >> _site/robots.txt && npm run build"
[context.production.environment]
  NODE_ENV = "production"
