apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-hello-world
  template:
    metadata:
      labels:
        name: kube-hello-world
    spec:
      containers:
      - name: hello-world-nodejs
        image: learnk8s/node-hello-world
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080